  export var map:any = {
    'THE_BARRENS': 'Forged in the Barrens',
    'DARKMOON_FAIRE': 'Darkmoon Faire',
    'SCHOLOMANCE': 'Scholomance Academy',
    'BLACK_TEMPLE': 'Ashes of Outland',
    'DEMON_HUNTER_INITIATE': 'Demon Hunter Initiate',
    'YEAR_OF_THE_DRAGON': 'Galakronds Awakening',
    'DRAGONS': 'Descent of Dragons',
    'ULDUM': 'Saviours of Uldum',
    'DALARAN': 'Rise of Shadows',
    'TROLL': 'Rastakhan\'s Rumble',
    'BOOMSDAY': 'The Boomsday Project',
    'GILNEAS': 'The Witchwood',
    'LOOTAPALOOZA': 'Kobolds & Catacombs',
    'ICECROWN': 'Knights of the Frozen Throne',
    'UNGORO': 'Journey to Un\'Goro',
    'GANGS': 'Mean Streets of Gadgetzan',
    'KARA': 'One Night in Karazhan',
    'OG': 'Whispers of the Old Gods',
    'LOE': 'League of Explorers',
    'TGT': 'The Grand Tournament',
    'BRM': 'Blackrock Mountain',
    'GVG': 'Goblins vs Gnomes',
    'NAXX': 'Naxxrammas',
    'LEGACY': 'Legacy',
    'VANILLA': 'Classic',
  }

  export var releaseMap:any = {
    'THE_BARRENS': 24,
    'DARKMOON_FAIRE': 23,
    'SCHOLOMANCE': 22,
    'BLACK_TEMPLE': 21,
    'DEMON_HUNTER_INITIATE': 20,
    'YEAR_OF_THE_DRAGON': 19,
    'DRAGONS': 18,
    'ULDUM': 17,
    'DALARAN': 16,
    'TROLL': 15,
    'BOOMSDAY': 14,
    'GILNEAS': 13,
    'LOOTAPALOOZA': 12,
    'ICECROWN': 11,
    'UNGORO': 10,
    'GANGS': 9,
    'KARA': 8,
    'OG': 7,
    'LOE': 6,
    'TGT': 5,
    'BRM': 4,
    'GVG': 3,
    'NAXX': 2,
    'LEGACY': 1,
    'VANILLA': 0,
  }